version: "2"

services:
  php:
    image: ${REGISTRY_URL}${REPOSITORY_NAME}php:${DOCKER_TAG}
    build:
      context: './../'
      dockerfile: 'docker/php/Dockerfile'
    expose:
      - 9000
    environment:
      - SYMFONY_ENV
      - PASSWORD_HASH_ALGORITHM=bcrypt
      - APP_ENV
      - APP_SECRET
      - DATABASE_URL
      - HOST
      - SERVICE_EMAIL
      - TARGET_HOST
      - TARGET_HOST_SCHEMA
      - API_VERSION
      - PHP_IDE_CONFIG=serverName=${TARGET_HOST}
      - MAILER_HOST
      - MAILER_PORT
      - MAILER_USER
      - MAILER_API_KEY
      - MAILER_ENCRYPTION
      - MAILER_SENDER
    volumes:
      - "../.:/app"
      - /app/var

  front:
    image: ${REGISTRY_URL}${REPOSITORY_NAME}front:${DOCKER_TAG}
    build: 'nginx'
    depends_on:
      - php
    ports:
      - 8080:80
    environment:
      - DEFAULT_DOMAIN=${TARGET_HOST}
      - VIRTUAL_HOST=test.docker
      - VIRTUAL_PORT=80
      - USE_CORS_PROXY=yes

  database:
    image: postgres:13
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASS}
      - PGPASSWORD=${DB_PASS}
    ports:
      - 5432:5432
    volumes:
      - databasevolume:/var/lib/postgresql/data

volumes:
  databasevolume:
    driver: local
