parameters:
    locale: 'en'
    storage.filesystem.prefix: 'test'
    tus.cache.dir:             '%kernel.cache_dir%/uploads_in_progress'
    api_prefix:                '/api'
    aws_s3_bucket:             '%env(AWS_S3_BUCKET)%'
    mailer_sender:             '%env(MAILER_SENDER)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'

    App\Application\Http\Controller\:
        resource: '../src/Application/Http/Controller'
        tags: ['controller.service_arguments']

    gedmo.listener.softdeleteable:
        class: Gedmo\SoftDeleteable\SoftDeleteableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    gedmo.listener.sortable:
        class: Gedmo\Sortable\SortableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    app.s3_client:
        lazy: true
        class: Aws\S3\S3Client
        arguments:
            - version: '2006-03-01'
              region: "%env(AWS_REGION)%"
              credentials:
                  key: "%env(AWS_KEY)%"
                  secret: "%env(AWS_SECRET)%"
